# Site settings
title: "jericodelfinado"
email: "jerico.delfinado@gmail.com"
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jericodelfinado.io" # the base hostname & protocol for your site

twitter_username: "jericodelfinado"
github_username: "jericodelfinado"

# Build settings
markdown: kramdown
