# General Settings
name: Jerico Caesar Delfinado
job_title: (Creative) Software Engineer
email: jerico.delfinado@gmail.com
description: I love solving problems. I like analyzing and coming up with solutions to grow and build products. I also have photography and graphic design as hobbies. Follow me on instagram or send me an email if you would like to start creating and building awesome stuff. 
avatar: https://www.gravatar.com/avatar/458e1e8282bcf9c02d53a926c30662b0?s=140
favicon: /favicon.ico
twitter_handler: jericodelfinado
#analytics_code: UA-XXXXXXX-2
#disqus: your_disqus_site

# Social Accounts
social_networks:
# -  { name: facebook, url: 'https://facebook.com' }
# -  { name: twitter, url: 'https://twitter.com/jericodelfinado' }
-  { name: instagram, url: 'https://instagram.com/jericodelfinado' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/jericodelfinado/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/jericodelfinado' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 0
show_email: 1
show_rss: 0
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""
blogurl: "/blog"

# Includes
include: ["_pages"]

# Outputting
permalink: /blog/:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/blog/page:num/" 

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

