baseURL = 'http://thisweekinphotos.com/'
languageCode = 'en-us'
title = 'This Week in Photos'
theme = 'hello-friend'
paginate = 5

content = "Hello"

[languages]
    [languages.en]
        title = "This Week in Photos"
        subtitle = "A weekly photo blog."
        keywords = "blog, photo"
        copyright = ""
        menuMore = "Show more"
        writtenBy = "by"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
        minuteReadingTime = "min read"
        dateFormatSingle = "2006-01-02"
        dateFormatList = "2006-01-02"

[languages.en.params.logo]
      logoText = "This Week in Photos"
      logoHomeLink = "/"

[languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
        weight = 2